### ISSUE TITLE
Doesn't work on reboot

### ISSUE THREAD

**Issue by daneandk** [vasyl91/DisplayMediaTitles#1]
I am using it on an android tablet. 
It's a great app with great features that I wanted! 
However, it works fine when first installed, but when I reboot the device, the app does not work. How can I solve this?

**Comment by vasyl91** [comment]
I'm about to release new version with auto start feature. Till then it should work again after manually opening the app after reboot.

**Comment by vasyl91** [comment]
Please check the latest update, it should work now. If it doesn't then I'm afraid that I can't help, I don't have a tablet so I cant reproduce it. BTW, on my phone (Redmi Note 8T) it works after rebooting even without restarting the app.

**Comment by daneandk** [comment]
Thank you so much for your efforts. 🙏
Even if you install a new version, the symptoms are the same. 
I think it's a permissions issue. 
This is because if I reboot, disable the 'notification listener' and 'battery optimization' permissions, 
and then allow each permission again, 
the app will work normally again.
How can I solve this.. Please help 🙏😢

**Comment by vasyl91** [comment]
It might be the question of Google Play or some other app that reverts these permissions (I found on the internet that in some cases Android Auto does that) or the Anrdoid setting itself. 
 - Turn off Play Protect and check this [answer](https://android.stackexchange.com/a/250427)
 - Check this [thread](https://xdaforums.com/t/app-battery-optimization-resetting-after-reboot.3872506/)
 - Try to grant "Modify system settings" permission, maybe that will be helpful.

If the above solutions don't work then try to google it. Find out what Android version you're using to get more accurate Google answers. 

Another possible solution is to convert the app to the system app. This requires root access.
