### ISSUE TITLE
Hello. I have a suggestion regarding the app.

### ISSUE THREAD

**Issue by rascapple** [vasyl91/DisplayMediaTitles#2]
I'm enjoying using the app.  
I have one suggestion.  

It would be great if users could change the font to their preferred font by supporting .ttf files.  

Font customization feature.

**Comment by vasyl91** [comment]
Quick research on the internet tells me that it should be possible with something like `Typeface typeface = Typeface.createFromAsset(getAssets(),"dir/filename.ttf");` Question of implementing file picker. I'll check that when I find some time.

**Comment by vasyl91** [comment]
[Latest release](https://github.com/vasyl91/Display-Media-Titles/releases/tag/v1.0.7) supports .ttf fonts. Enjoy ;)

**Comment by rascapple** [comment]
ttf supports , thank you

2024년 12월 8일 (일) 02:14, Hubert ***@***.***>님이 작성:
