### ISSUE TITLE
Hello, I have one feature suggestion.

### ISSUE THREAD

**Issue by rascapple** [vasyl91/DisplayMediaTitles#4]
Can you add a shadow effect to enhance the font's readability?

thank you.

**Comment by vasyl91** [comment]
I was thinking about adding view twice in non system apps to make it more visible, I'll try to add that, but can't promise anything

**Comment by rascapple** [comment]
> I was thinking about adding view twice in non system apps to make it more visible, I'll try to add that, but can't promise anything 

Thank you for your response.

**Comment by rascapple** [comment]
First of all, thank you for incorporating features like the recent TTF font functionality and the option to hide artist names. 

I have a suggestion, dear developer. 

Currently, when the sentence length is too long, an automatic scrolling effect to the left occurs. It would be great if we could adjust the speed of this scrolling effect. 

At the moment, it feels a bit slow, and there are times when I wish to make it faster. 

I would appreciate it if you could review this and include it in the next update if possible.

**Comment by vasyl91** [comment]
Not possible. If you want to use that app to display lyrics, please pick your own fork and modify it to your needs.

**Comment by vasyl91** [comment]
Latest release adds the double view function. I consider the app as complete and don't plan or intend to add any more features, therefore if you want other modifications, please add them yourself.

**Comment by rascapple** [comment]
Thank you

2024년 12월 19일 (목) 19:38, Hubert ***@***.***>님이 작성:
